content:
    - name: quiz_files
      label: All Quiz Files
      type: collection
      path: app/public/quiz
      format: json
      fields:
          - type: object
            name: "Chapters"
            label: Chapter info
            fields:
                - name: chapter
                  label: Chapter (Number)
                  type: number

                - name: vocabulary
                  label: Quiz List
                  type: object
                  fields:
                      - name: id
                        label: UUID
                        type: string
                      - name: expression
                        label: Question
                        type: string

                      - name: definitions
                        label: Answer
                        type: text
