content:
    - name: quiz_files
      label: All Quiz Files
      type: collection
      path: app/public/quiz
      format: json
      list: true
      fields:
          - name: chapter
            label: Chapter number
            type: number
          - name: vocabulary
            label: Vocabulary
            type: object
            list: true
            fields:
                - name: id
                  label: UUID
                  type: string
                - name: expression
                  label: Expression
                  type: string
                - name: definitions
                  label: Definitions
                  type: string
                  list: true
